### ISSUE TITLE
Sample Code Crashes Unity Editor on Windows when connection with device is lost while recording

### ISSUE THREAD

**Issue by ClaytonHughes** [biosignalsplux/unity-sample#1]
I don't know whether this issue is specific to the sample or is inherent to the library, but I have reliable reproduction steps:

1. Open the unity-sample project with Unity 2018.3.11f1 x64 on Windows 10 (Version 1809, Build 17763.379) (I haven't tried other versions of Unity or OS)
2. Open the "AboutWindow" scene.
3. Launch the application in-editor with the play button.
5. Find Devices, Connect to a device (I have a 4-port plux)
6. Begin recording data from channel one (it hardly seems relevant but I was using an EDA and had nothing in any of the other channels)
7. Walk a fair distance away from the computer with the plux (50-100 meters?), so as to disrupt communications between them. (Presumably you could also put it in a Faraday cage or something.)
8. The plux will continue to record data until the Unity Editor crashes. Nothing is logged to the Console or log file after `Acquisition Thread Started with Success !`.

**Comment by GRamosPlux** [comment]
Dear **ClaytonHughes**,

Thank you very much for your detailed explanation and kind support to our project !
After replicating the reported experimental procedure we reached the same "crash", your contribute was really useful.

Essentially we were not dealing with unexpected disconnect events, namely, the ones caused by the lost of connection between the computer and the PLUX device.
Meanwhile we implemented some corrections (to fix this issue) and the first tests were positive.

You can access the new version on our repository !

We will carefully wait for your feedback, if you detect additional issues, please, do not hesitate to present them to us.

                   My best and sincere regards,
                   GRamosPlux
